USE ticketing;

ALTER TABLE customer
    DROP COLUMN user_id,
    DROP COLUMN created_at,
    DROP COLUMN updated_at;

ALTER TABLE customer
    ADD COLUMN user_id BIGINT UNIQUE NOT NULL,
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
